# version: '3'
 
# services:
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_USER='postgres'
#       - POSTGRES_PASSWORD='@dmin1234'
#       - POSTGRES_DB='petmatedb'
#     expose:
#       - "5432"
#   web:
#     build: .
#     # command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/petmate-docker
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db


# DEVELOPMENT CONFIGS

version: "3"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres"
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data