# Generated by Django 2.2.7 on 2019-12-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petlisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pet', models.TextField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('gender', models.TextField(max_length=7)),
                ('about', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_listed', models.DateTimeField()),
            ],
        ),
    ]
