# Generated by Django 2.2.7 on 2020-01-05 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petlisting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petlisting',
            name='image',
        ),
        migrations.AddField(
            model_name='petlisting',
            name='interested_pets',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='petlisting',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='date_listed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='gender',
            field=models.TextField(max_length=30),
        ),
    ]
